In [ ]:
# 216270307045
# Hitarth M Hindocha
# to convert a NumPy array to a Pandas series

#######################################################
import pandas as pd
import numpy as np

a=np.arange(1,11)

print("Array is ",a)
var=pd.Series(a)

print("\nSeries is \n")
print(var)

In [ ]:
# 216270307045
# Hitarth M Hindocha
# to convert the first column of a DataFrame as a Series

#######################################################
import pandas as pd

info={"calories": [420, 380, 390],
      "duration ":[45,60,55]
     }
df=pd.DataFrame(data=info)
print("Data Frame is \n")
print(df)

print("\nFirst Column as Series is ")

print()
df2=df.iloc[0:,0]
print(df2)

#######################################################

In [ ]:
# 216270307045
# Hitarth M Hindocha
# to create the mean and standard deviation of the data of a given Series

#######################################################

import pandas as pd

a=[1,7,2,3,4]
ser=pd.Series(a)
print("Series is \n")
print(ser)

print("\nMean of data is ",ser.mean())
print("Standard Deviation of data is ",ser.std())

#######################################################

In [ ]:
# 216270307045
# Hitarth M Hindocha
# to sort a given Series
#######################################################

import pandas as pd

data=[10,20,50,1,100,2,5,99]
print("Series is \n")
ser=pd.Series(data)

print(ser)
print("Series After Sorting Values  \n")
print(ser.sort_values())

#######################################################